name: ataa
description: Ataa is a non profit app that helps people to get their over needs food to anyone that maybe can't find any food to eat.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  font_awesome_flutter: ^9.1.0
  numberpicker: ^2.1.1
  google_maps_flutter: ^2.0.6
  geolocator: ^7.4.0
  shared_preferences: ^2.0.6
  http: ^0.13.3
  url_launcher: ^6.0.9
  lottie: ^1.1.0
  provider: ^6.0.0
  firebase_core: ^1.5.0
  firebase_analytics: ^8.3.0
  firebase_crashlytics: ^2.2.0
  google_mobile_ads: ^0.13.3
  cool_alert: ^1.1.0
  dio: ^4.0.0
  cached_network_image: ^3.2.0
#  hive: ^2.0.5
  intl: ^0.17.0
  pusher_client: ^2.0.0
  flutter_lints: ^1.0.4
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/
  - assets/animations/
  - dark.json
  fonts:
    - family: "OpenSans"
      fonts:
        - asset: "fonts/OpenSans-Light.ttf"
          style: "normal"
          weight: 300
        - asset: "fonts/OpenSans-LightItalic.ttf"
          style: "italic"
          weight: 300
        - asset: "fonts/OpenSans-Regular.ttf"
          style: "normal"
          weight: 400
        - asset: "fonts/OpenSans-Italic.ttf"
          style: "italic"
          weight: 400
        - asset: "fonts/OpenSans-SemiBold.ttf"
          style: "normal"
          weight: 600
        - asset: "fonts/OpenSans-SemiBoldItalic.ttf"
          style: "italic"
          weight: 600
        - asset: "fonts/OpenSans-Bold.ttf"
          style: "normal"
          weight: 700
        - asset: "fonts/OpenSans-BoldItalic.ttf"
          style: "italic"
          weight: 700
        - asset: "fonts/OpenSans-ExtraBold.ttf"
          style: "normal"
          weight: 800
        - asset: "fonts/OpenSans-ExtraBoldItalic.ttf"
          style: "italic"
          weight: 800
    - family: "Delius"
      fonts:
        - asset: "fonts/Delius-Regular.ttf"
          style: "normal"
          weight: 400
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
