name: feedme
description: Feedme is a non profit app that helps people to get their over needs food to anyone that maybe can't find any food to eat.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  google_maps_flutter: ^0.5.25+3
  geolocator: ^5.3.0
  toast: ^0.1.5
  http: ^0.12.0+4
  shared_preferences: ^0.5.10
  url_launcher: ^5.2.5
  google_fonts: ^1.0.0
  firebase_analytics: ^6.0.0
  firebase_crashlytics: ^0.1.4+1
  firebase_core: ^0.5.0
  firebase_admob: ^0.9.0
  lottie: ^0.5.1
  provider: ^4.3.2+1
  facebook_audience_network: ^0.7.0
  font_awesome_flutter: ^8.8.1
  numberpicker: ^1.2.0
  cloud_firestore: ^0.14.0+2
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/
  - assets/animations/
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
